# Comprehensive AKC breed name to GitHub folder mapping
# Auto-generated mapping with 94.4% coverage (184 out of 195 breeds)
# Unmapped breeds will use fallback Unsplash images

BREED_FOLDER_MAP = {
    'Affenpinschers': 'affenpinscher dog',
    'Afghan Hounds': 'afghan hound dog',
    'Airedale Terriers': 'airedale terrier dog',
    'Akitas': 'akita dog',
    'Alaskan Malamutes': 'alaskan malamute dog',
    'American English Coonhounds': 'black and tan coonhound dog',
    'American Eskimo Dogs': 'canadian eskimo dog',
    'American Hairless Terriers': 'peruvian hairless dog',
    'American English Coonhounds': 'american foxhound dog',
    'American Eskimo Dogs': 'american akita dog',
    'American Foxhounds': 'american foxhound dog',
    'American Hairless Terriers': 'american staffordshire terrier dog',
    'American Staffordshire Terriers': 'american staffordshire terrier dog',
    'Anatolian Shepherd Dogs': 'australian shepherd dog',
    'Australian Cattle Dogs': 'australian cattle dog',
    'Australian Shepherds': 'australian shepherd dog',
    'Australian Terriers': 'australian terrier dog',
    'Azawakhs': 'azawakh dog',
    'Basenjis': 'basenji dog',
    'Basset Hounds': 'basset hound dog',
    'Beagles': 'beagle dog',
    'Bearded Collies': 'bearded collie dog',
    'Beaucerons': 'berger de beauce dog',
    'Bedlington Terriers': 'bedlington terrier dog',
    'Belgian Malinois': 'belgian shepherd dog',
    'Belgian Tervuren': 'belgian shepherd dog',
    'Belgian Sheepdogs': 'belgian shepherd dog',
    'Belgian Tervuren': 'brazilian terrier dog',
    'Bergamasco Sheepdogs': 'bergamasco shepherd dog',
    'Berger Picards': 'blue picardy spaniel dog',
    'Berger Picards': 'leonberger dog',
    'Bernese Mountain Dogs': 'bernese mountain dog',
    'Bichons Frises': 'bichon frise dog',
    'Black Russian Terriers': 'russian black terrier dog',
    'Black Russian Terriers': 'jack russell terrier dog',
    'Black and Tan Coonhounds': 'black and tan coonhound dog',
    'Bloodhounds': 'bloodhound dog',
    'Bluetick Coonhounds': 'black and tan coonhound dog',
    'Bluetick Coonhounds': 'black and tan coonhound dog',
    'Boerboels': 'boxer dog',
    'Border Collies': 'border collie dog',
    'Border Terriers': 'border terrier dog',
    'Borzois': 'borzoi - russian hunting sighthound dog',
    'Boston Terriers': 'boston terrier dog',
    'Bouviers des Flandres': 'bouvier des flandres dog',
    'Boxers': 'boxer dog',
    'Briards': 'briard dog',
    'Brittanys': 'brittany spaniel dog',
    'Brussels Griffons': 'blue gascony griffon dog',
    'Brussels Griffons': 'bullmastiff dog',
    'Bulldogs': 'bulldog',
    'Bullmastiffs': 'bullmastiff dog',
    'Bull Terriers': 'bull terrier dog',
    'Cairn Terriers': 'cairn terrier dog',
    'Canaan Dogs': 'canaan dog',
    'Cane Corso': 'italian cane corso dog',
    'Cane Corso': 'italian cane corso dog',
    'Cardigan Welsh Corgis': 'welsh corgi (cardigan) dog',
    'Cardigan Welsh Corgis': 'picardy spaniel dog',
    'Cavalier King Charles Spaniels': 'cavalier king charles spaniel dog',
    'Cesky Terriers': 'cesky terrier dog',
    'Chihuahuas': 'chihuahua dog',
    'Chinese Shar-Pei': 'shar pei dog',
    'Chinese Crested': 'chinese crested dog',
    'Chow Chows': 'chow chow dog',
    'Cirnechi dell\'Etna': 'cirneco dell\'etna dog',
    'Collies': 'collie smooth dog',
    'Coton de Tulear': 'coton de tulear dog',
    'Dachshunds': 'dachshund dog',
    'Dalmatians': 'dalmatian dog',
    'Dandie Dinmont Terriers': 'dandie dinmont terrier dog',
    'Doberman Pinschers': 'german pinscher dog',
    'Dogo Argentinos': 'dogo argentino',
    'Dogues de Bordeaux': 'dogue de bordeaux',
    'English Foxhounds': 'english foxhound dog',
    'English Toy Spaniels': 'english cocker spaniel dog',
    'Entlebucher Mountain Dogs': 'estrela mountain dog',
    'Finnish Lapphunds': 'finnish lapponian dog',
    'Finnish Spitz': 'finnish spitz dog',
    'Fox Terriers (Smooth)': 'fox terrier (smooth) dog',
    'Fox Terriers (Wire)': 'fox terrier (wire) dog',
    'French Bulldogs': 'french bulldog',
    'German Pinschers': 'german pinscher dog',
    'German Shepherd Dogs': 'german shepherd dog',
    'Giant Schnauzers': 'giant schnauzer dog',
    'Glen of Imaal Terriers': 'irish glen of imaal terrier dog',
    'Grand Basset Griffon Vendeens': 'grand basset griffon vendeen dog',
    'Greater Swiss Mountain Dogs': 'great swiss mountain dog',
    'Great Danes': 'great dane dog',
    'Great Pyrenees': 'great dane dog',
    'Greyhounds': 'greyhound dog',
    'Harriers': 'harrier dog',
    'Havanese': 'havanese dog',
    'Ibizan Hounds': 'serbian hound dog',
    'Icelandic Sheepdogs': 'icelandic sheepdog',
    'Irish Terriers': 'irish terrier dog',
    'Irish Wolfhounds': 'irish wolfhound dog',
    'Italian Greyhounds': 'italian sighthound dog',
    'Japanese Chin': 'japanese chin dog',
    'Kerry Blue Terriers': 'kerry blue terrier dog',
    'Komondorok': 'komondor dog',
    'Kuvaszok': 'kuvasz dog',
    'Lakeland Terriers': 'lakeland terrier dog',
    'Leonbergers': 'leonberger dog',
    'Lhasa Apsos': 'lhasa apso dog',
    'Maltese': 'maltese dog',
    'Manchester Terriers': 'manchester terrier dog',
    'Mastiffs': 'mastiff dog',
    'Miniature American Shepherds': 'miniature american shepherd dog',
    'Miniature Bull Terriers': 'miniature bull terrier dog',
    'Miniature Pinschers': 'miniature pinscher dog',
    'Miniature Schnauzers': 'miniature schnauzer dog',
    'Neapolitan Mastiffs': 'neapolitan mastiff dog',
    'Nederlandse Kooikerhondjes': 'nederlandse kooikerhondje dog',
    'Newfoundlands': 'newfoundland dog',
    'Norfolk Terriers': 'norfolk terrier dog',
    'Norwegian Buhunds': 'norwegian buhund dog',
    'Norwegian Elkhounds': 'norwegian elkhound grey dog',
    'Norwegian Lundehunds': 'norwegian lundehund dog',
    'Norwich Terriers': 'norwich terrier dog',
    'Old English Sheepdogs': 'old english sheepdog',
    'Otterhounds': 'otterhound dog',
    'Parson Russell Terriers': 'parson russell terrier dog',
    'Pekingese': 'pekingese dog',
    'Petits Bassets Griffons Vendeens': 'petit basset griffon vendeen dog',
    'Pharaoh Hounds': 'pharaoh hound dog',
    'Plott Hounds': 'otterhound dog',
    'Pointers': 'pudelpointer dog',
    'Pointers (German Shorthaired)': 'german short- haired pointing dog',
    'Pointers (German Wirehaired)': 'german wire- haired pointing dog',
    'Polish Lowland Sheepdogs': 'polish lowland sheepdog',
    'Pomeranians': 'eurasian dog',
    'Poodles': 'poodle dog',
    'Portuguese Podengo Pequenos': 'portuguese pointing dog',
    'Portuguese Water Dogs': 'portuguese water dog',
    'Pugs': 'pug dog',
    'Pulik': 'puli dog',
    'Pumik': 'pumi dog',
    'Pyrenean Shepherds': 'german shepherd dog',
    'Rat Terriers': 'irish terrier dog',
    'Redbone Coonhounds': 'tyrolean hound dog',
    'Retrievers (Chesapeake Bay)': 'chesapeake bay retriever dog',
    'Retrievers (Curly-Coated)': 'curly coated retriever dog',
    'Retrievers (Flat-Coated)': 'flat coated retriever dog',
    'Retrievers (Golden)': 'golden retriever dog',
    'Retrievers (Labrador)': 'labrador retriever dog',
    'Retrievers (Nova Scotia Duck Tolling)': 'nova scotia duck tolling retriever dog',
    'Rhodesian Ridgebacks': 'rhodesian ridgeback dog',
    'Rottweilers': 'rottweiler dog',
    'Russell Terriers': 'jack russell terrier dog',
    'Salukis': 'saluki dog',
    'Samoyeds': 'samoyed dog',
    'Schipperkes': 'schipperke dog',
    'Scottish Deerhounds': 'otterhound dog',
    'Scottish Terriers': 'scottish terrier dog',
    'Sealyham Terriers': 'sealyham terrier dog',
    'Setters (Gordon)': 'skye terrier dog',
    'Shetland Sheepdogs': 'shetland sheepdog',
    'Shiba Inu': 'shiba dog',
    'Shih Tzu': 'shih tzu dog',
    'Siberian Huskies': 'siberian husky dog',
    'Silky Terriers': 'skye terrier dog',
    'Skye Terriers': 'skye terrier dog',
    'Sloughis': 'sloughi dog',
    'Soft Coated Wheaten Terriers': 'irish soft coated wheaten terrier dog',
    'Spaniels (American Water)': 'spanish water dog',
    'Spaniels (English Cocker)': 'english cocker spaniel dog',
    'Spaniels (English Springer)': 'english springer spaniel dog',
    'Spaniels (Irish Water)': 'spanish water dog',
    'Spaniels (Welsh Springer)': 'welsh springer spaniel dog',
    'Spanish Water Dogs': 'spanish water dog',
    'St. Bernards': 'st. bernard dog',
    'Staffordshire Bull Terriers': 'staffordshire bull terrier dog',
    'Standard Schnauzers': 'giant schnauzer dog',
    'Swedish Vallhunds': 'swedish vallhund dog',
    'Tibetan Mastiffs': 'tibetan mastiff dog',
    'Tibetan Spaniels': 'tibetan spaniel dog',
    'Tibetan Terriers': 'tibetan terrier dog',
    'Toy Fox Terriers': 'norfolk terrier dog',
    'Weimaraners': 'weimaraner dog',
    'Welsh Terriers': 'welsh terrier dog',
    'West Highland White Terriers': 'west highland white terrier dog',
    'Whippets': 'whippet dog',
    'Wirehaired Pointing Griffons': 'wire-haired pointing griffon korthals dog',
    'Wirehaired Vizslas': 'wirehaired slovakian pointer dog',
    'Xoloitzcuintli': 'xoloitzcuintle dog',
    'Yorkshire Terriers': 'yorkshire terrier dog',
}
