name: pawmatcher
region: nyc
services:
  - name: web
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/pawmatcher
    source_dir: /
    run_command: gunicorn --worker-tmp-dir /dev/shm app:app
    http_port: 8080
    envs:
      - key: AZURE_OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AZURE_OPENAI_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        scope: RUN_TIME
        type: SECRET
      - key: AZURE_STORAGE_ACCOUNT
        scope: RUN_TIME
        value: pawmatchstorage2024
      - key: AZURE_STORAGE_CONTAINER
        scope: RUN_TIME
        value: dog-breeds
